#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-spdx_tools
Version  : 0.8.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/28/2d/c3982e35bea2be16c529074a668acd851e8381acd9e2acaa830cc36bd039/spdx-tools-0.8.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/28/2d/c3982e35bea2be16c529074a668acd851e8381acd9e2acaa830cc36bd039/spdx-tools-0.8.1.tar.gz
Summary  : SPDX parser and tools.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-spdx_tools-bin = %{version}-%{release}
Requires: pypi-spdx_tools-license = %{version}-%{release}
Requires: pypi-spdx_tools-python = %{version}-%{release}
Requires: pypi-spdx_tools-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Python library to parse, validate and create SPDX documents
CI status (Linux, macOS and Windows): [![Install and Test][1]][2]

%package bin
Summary: bin components for the pypi-spdx_tools package.
Group: Binaries
Requires: pypi-spdx_tools-license = %{version}-%{release}

%description bin
bin components for the pypi-spdx_tools package.


%package license
Summary: license components for the pypi-spdx_tools package.
Group: Default

%description license
license components for the pypi-spdx_tools package.


%package python
Summary: python components for the pypi-spdx_tools package.
Group: Default
Requires: pypi-spdx_tools-python3 = %{version}-%{release}

%description python
python components for the pypi-spdx_tools package.


%package python3
Summary: python3 components for the pypi-spdx_tools package.
Group: Default
Requires: python3-core
Provides: pypi(spdx_tools)
Requires: pypi(beartype)
Requires: pypi(click)
Requires: pypi(license_expression)
Requires: pypi(ply)
Requires: pypi(pyyaml)
Requires: pypi(rdflib)
Requires: pypi(semantic_version)
Requires: pypi(uritools)
Requires: pypi(xmltodict)

%description python3
python3 components for the pypi-spdx_tools package.


%prep
%setup -q -n spdx-tools-0.8.1
cd %{_builddir}/spdx-tools-0.8.1
pushd ..
cp -a spdx-tools-0.8.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692893854
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-spdx_tools
cp %{_builddir}/spdx-tools-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-spdx_tools/81fd98ae93fd5e0a79ebca20ec8881478fe402a8 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyspdxtools
/usr/bin/pyspdxtools3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-spdx_tools/81fd98ae93fd5e0a79ebca20ec8881478fe402a8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
